services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: "azurite"
    hostname: azurite
    restart: unless-stopped
    command: >
      azurite
      --location /workspace
      --debug /workspace/debug.log
      --blobHost 0.0.0.0
      --blobPort 10000
      --queueHost 0.0.0.0
      --queuePort 10001
      --tableHost 0.0.0.0
      --tablePort 10002
      --loose
      --skipApiVersionCheck
      --disableProductStyleUrl
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - ./azurite-data:/workspace  # Persistent storage to a local directory
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==  # Example account
    networks:
      - azurite-network
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 0.0.0.0 10000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  azurite-network:
    driver: bridge
